---
services:
  api:
    container_name: "finances-api"
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/finances
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks:
      - web

  db:
    container_name: "finances-postgres"
    build:
      context: .
      dockerfile: db/Dockerfile
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=finances
    ports:
      - "5432:5432"
    networks:
      - web

# finance_tracker:
#   build:
#     context: .
#     dockerfile:

networks:
  web:
